export default{
    LOGIN:"LOGIN",
    PROFILE:"PROFILE",
    LOGOUT:"LOGOUT",
    CLEAR_REDUX_STATE:"CLEAR_REDUX_STATE",
    SCANNER:"SCANNER",
    ATTENDANCE:"ATTENDANCE",
    APPLIST:"APPLIST"
}